In [1]:
#Importamos las librerias pandas, numpy y matplotlib respectivamente
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
#Carga desde un archivo .csv sin indice
#data = pd.read_csv('inmuebles2.csv')
data = pd.read_excel('Principales_Canales.xlsx')
data.head(5)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34
0,NaN,NaN,NaN,Datos erroneos no confiables de Sale-U,NaN,NaN,NaN,-,Sin datos,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Ventas X Mes,Ventas Reportadas,12,7,8,13,6,21,17,17,...,38,30,41,41,35,37,NaN,NaN,NaN,NaN
3,Piso,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Conversion,NaN,NaN
4,Piso,"Febrero, 24","Marzo, 24","Abril, 24","Mayo, 24","Junio, 24","Julio, 24","Agosto, 24","Septiembre, 24","Octubre, 24",...,"Febrero, 26","Marzo, 26","Abril, 26","Mayo, 26","Junio, 26","Julio,26",NaN,Historica,Año actual,Ultimos 3 meses

In [5]:
#Identificar valores nulos por columna
valores_nulos=data.isnull().sum()
valores_nulos

Unnamed: 0     12
Unnamed: 1     25
Unnamed: 2     20
Unnamed: 3     18
Unnamed: 4     19
Unnamed: 5     17
Unnamed: 6     17
Unnamed: 7     17
Unnamed: 8     16
Unnamed: 9     17
Unnamed: 10    17
Unnamed: 11    16
Unnamed: 12    15
Unnamed: 13    12
Unnamed: 14    12
Unnamed: 15    12
Unnamed: 16    12
Unnamed: 17    15
Unnamed: 18    15
Unnamed: 19    13
Unnamed: 20    13
Unnamed: 21    13
Unnamed: 22    13
Unnamed: 23    12
Unnamed: 24    11
Unnamed: 25    21
Unnamed: 26    21
Unnamed: 27    21
Unnamed: 28    21
Unnamed: 29    21
Unnamed: 30    24
Unnamed: 31    58
Unnamed: 32    28
Unnamed: 33    40
Unnamed: 34    40
dtype: int64

In [7]:
#Identificar valores nulos por dataframe
valores_nulos=data.isnull().sum().sum()
valores_nulos

np.int64(674)

In [11]:
#Ver el número de filas en el archivo
data.shape[0]

58

In [14]:
# Eliminar columna innecesarias

#La columna "Unnamed: 31" tiene 5 celdas NaN
#Ya que el archivo tiene una extensión de 58 filas
#es mejor eliminar toda la columna

data1 = data.drop(["Unnamed: 31"], axis=1)

data1.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 32,Unnamed: 33,Unnamed: 34
0,NaN,NaN,NaN,Datos erroneos no confiables de Sale-U,NaN,NaN,NaN,-,Sin datos,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Ventas X Mes,Ventas Reportadas,12,7,8,13,6,21,17,17,...,34,38,30,41,41,35,37,NaN,NaN,NaN
3,Piso,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Conversion,NaN,NaN
4,Piso,"Febrero, 24","Marzo, 24","Abril, 24","Mayo, 24","Junio, 24","Julio, 24","Agosto, 24","Septiembre, 24","Octubre, 24",...,"Enero, 26","Febrero, 26","Marzo, 26","Abril, 26","Mayo, 26","Junio, 26","Julio,26",Historica,Año actual,Ultimos 3 meses

In [ ]:
# Sustituir valores nulos por un string en concreto

#Al ser una columna de texto, solo hace falta sustituirlos por un texto especifico.
data1["Unnamed: 0"] = data1["Unnamed: 0"].fillna("Sin dato")

In [17]:
# Sustituir valores nulos por un valor numérico en concreto

#Al ser números representativos y no calculados, los sustituimos por valores fijos.
data1["Unnamed: 1"] = data1["Unnamed: 1"].fillna(0)

In [19]:
# Sustituir valores nulos de las columnas mensuales por 0

#En este caso, el 0 funcionaría como un valor "simbolico" que
#significaria o representaria la ausencia de información
#para dicha columna

data1.loc[:, "Unnamed: 1":"Unnamed: 30"] = data1.loc[:, "Unnamed: 1":"Unnamed: 30"].fillna(0)

In [23]:
# Sustituir valores nulos de la columna Unnamed: 32 por un string

# Esta columna contiene datos de resumen y diferentes tipos de información
# por lo que "Sin dato" representa la ausencia de información sin alterar los valores existentes

data1["Unnamed: 32"] = data1["Unnamed: 32"].fillna("Sin dato")

In [ ]:
# Sustituir valores nulos de la columna Unnamed: 33 por un string especifico.

#Al ser una columna de texto, solo hace falta sustituirlos por un texto especifico

data1["Unnamed: 33"] = data1["Unnamed: 33"].fillna("Sin dato")

In [ ]:
# Sustituir valores nulos de la columna Unnamed: 34 por un string especifico.

#Al ser una columna de texto, solo hace falta sustituirlos por un texto especifico

data1["Unnamed: 34"] = data1["Unnamed: 34"].fillna("Sin dato")

In [ ]:
#Comprobamos cantidad de valores nulos luego de la limpieza.

valores_nulos=data1.isnull().sum().sum()
valores_nulos

np.int64(0)

In [27]:
#Generar CSV limpio

data1.to_csv("Principales_Canales_Limpio.csv", index=False)