In [1]:
#Importamos las librerias pandas, numpy y matplotlib respectivamente
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#Carga desde un archivo .xlsx sin indice
df = pd.read_excel('SDC.xlsx')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 44 entries, 0 to 43
Data columns (total 37 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Ventas       34 non-null     str
 1   Unnamed: 1   23 non-null     object
 2   12           23 non-null     object
 3   7            23 non-null     object
 4   8            23 non-null     object
 5   13           23 non-null     object
 6   6            23 non-null     object
 7   21           23 non-null     object
 8   17           23 non-null     object
 9   17.1         22 non-null     object
 10  23           23 non-null     object
 11  22           22 non-null     object
 12  32           22 non-null     object
 13  26           22 non-null     object
 14  20           22 non-null     object
 15  30           22 non-null     object
 16  30.1         22 non-null     object
 17  34           28 non-null     object
 18  40           27 non-null     object
 19  36           28 non-null     object
 20  27           26 non-null     object
 21  0            30 non-null     object
 22  27.1         26 non-null     object
 23  41           27 non-null     object
 24  40.1         23 non-null     object
 25  42           27 non-null     object
 26  34.1         26 non-null     object
 27  38           27 non-null     object
 28  30.2         24 non-null     object
 29  41.1         26 non-null     object
 30  41.2         26 non-null     object
 31  35           17 non-null     object
 32  Unnamed: 32  33 non-null     object
 33  Unnamed: 33  24 non-null     object
 34  Unnamed: 34  8 non-null      object
 35  Unnamed: 35  5 non-null      float64
 36  Unnamed: 36  2 non-null      float64
dtypes: float64(2), object(34), str(1)
memory usage: 12.8+ KB

In [3]:
df

,Ventas,Unnamed: 1,12,7,8,13,6,21,17,17.1,...,38,30.2,41.1,41.2,35,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Indicador,"Enero, 24","Febrero, 24","Marzo, 24","Abril, 24","Mayo, 24","Junio, 24","Julio, 24","Agosto, 24","Septiembre, 24",...,"Marzo, 26","Abril, 26","Mayo,26","Junio, 26","Julio,26",Total 2024,Total 2025,Total 2026,NaN,NaN
2,Generadas,5,6,11,23,26,43,55,36,56,...,85,74,95,82,32,519,1178,450,1697.0,0.392457
3,Aprobadas,1,2,7,14,8,13,30,19,26,...,41,42,44,35,12,215,451,201,666.0,0.509009
4,Condicionadas,0,0,1,0,4,0,3,0,1,...,14,16,17,10,9,100,287,102,387.0,NaN
5,Rechazadas,4,4,4,9,14,22,17,13,13,...,30,16,30,33,9,163,392,137,555.0,NaN
6,Formalizadas,1,1,5,11,3,6,17,9,7,...,18,16,19,13,4,105,234,91,339.0,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,% de Aprobación,0.2,0.333333,0.636364,0.608696,0.307692,0.302326,0.545455,0.527778,0.464286,...,0.482353,0.567568,0.463158,0.426829,0.375,0.414258,0.382852,0.446667,NaN,NaN
9,% de Formalizacion,1,0.5,0.714286,0.785714,0.375,0.461538,0.566667,0.473684,0.269231,...,0.439024,0.380952,0.431818,0.371429,0.333333,0.488372,0.518847,0.452736,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,N.º de solicitudes ingresadas por financiera,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Financiera,0,0,0,0,0,0,0,0,51,...,85,74,95,82,32,TOTAL,% PARTICIPACION,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.063245,NaN,NaN,NaN
15,ABC,-,-,-,-,-,-,-,-,-,...,NaN,NaN,NaN,NaN,NaN,1,0.000518,NaN,NaN,NaN
16,Afirme,-,-,-,-,-,-,-,-,18,...,NaN,NaN,NaN,NaN,NaN,121,0.062727,NaN,NaN,NaN
17,Banorte,-,-,-,-,-,-,-,-,1,...,33,33,34,15,10,790,0.409539,NaN,NaN,NaN
18,BBVA,-,-,-,-,-,-,-,-,12,...,12,7,11,16,3,202,0.104717,NaN,NaN,NaN
19,Ensueño,-,-,-,-,-,-,-,-,-,...,3,1,8,8,7,144,0.07465,NaN,NaN,NaN
20,FinanMadrid,-,-,-,-,-,-,-,-,NaN,...,NaN,NaN,NaN,NaN,NaN,2,0.001037,NaN,NaN,NaN
21,INBURSA,-,-,-,-,-,-,-,-,-,...,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN
22,MSTART,-,-,-,-,-,-,-,-,-,...,9,5,11,6,1,156,0.080871,NaN,NaN,NaN
23,Nexu,-,-,-,-,-,-,-,-,19,...,NaN,NaN,NaN,NaN,NaN,135,0.069984,NaN,NaN,NaN
24,Santander,-,-,-,-,-,-,-,-,1,...,25,21,18,30,7,442,0.229134,NaN,NaN,NaN
25,Scotiabank,-,-,-,-,-,-,-,-,-,...,1,3,9,6,4,41,0.021255,NaN,NaN,NaN
26,Sumafin,-,-,-,-,-,-,-,-,-,...,1,NaN,NaN,NaN,NaN,7,0.003629,NaN,NaN,NaN
27,Bajio,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1,NaN,NaN,NaN,NaN,1,0.000518,NaN,NaN,NaN
28,Kuna,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,4,4,1,NaN,9,0.004666,NaN,NaN,NaN
29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,Motivos de SDC No autorizadas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,NaN,"Enero, 24","Febrero, 24","Marzo, 24","Abril, 24","Mayo, 24","Junio, 24","Julio, 24","Agosto, 24","Septiembre, 24",...,"Marzo, 26","Abril, 26","Mayo,26","Junio, 26","Julio,26",Total,NaN,NaN,NaN,NaN
32,Mal Buro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,15,12,12,22,NaN,311,NaN,NaN,NaN,NaN
33,Score bajo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10,4,10,4,NaN,66,NaN,NaN,NaN,NaN
34,Capacidad de pago,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3,NaN,6,6,NaN,17,NaN,NaN,NaN,NaN
35,Otros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2,NaN,1,1,NaN,7,NaN,NaN,NaN,NaN
36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,Motivos de SDC No formaliadas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,NaN,"Enero, 24","Febrero, 24","Marzo, 24","Abril, 24","Mayo, 24","Junio, 24","Julio, 24","Agosto, 24","Septiembre, 24",...,"Marzo, 26","Abril, 26","Mayo,26","Junio, 26","Julio,26",Total,NaN,NaN,NaN,NaN
40,Compra en otro lado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1,2,2,2,NaN,44,NaN,NaN,NaN,NaN
41,Falta importe para enganche,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,3,1,2,NaN,6,NaN,NaN,NaN,NaN
42,Espera comprar en futuro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4,10,1,7,NaN,41,NaN,NaN,NaN,NaN
43,Otros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11,3,9,5,NaN,41,NaN,NaN,NaN,NaN

In [4]:
#Eliminar primera fila o filas innecesarias
df1= pd.read_excel('SDC.xlsx', skiprows=2)

In [5]:
#Eliminar columnas innecesarias
#axis = 1 para columnas
#axis = 0 para filas
df2= df1.drop(['Unnamed: 35', 'Unnamed: 36'], axis=1)

In [6]:
# Elimina filas donde la columna Indicador sea NaN
df3 = df2.dropna(subset=['Indicador'])
df3

,Indicador,"Enero, 24","Febrero, 24","Marzo, 24","Abril, 24","Mayo, 24","Junio, 24","Julio, 24","Agosto, 24","Septiembre, 24",...,"Enero, 26","Febrero, 26","Marzo, 26","Abril, 26","Mayo,26","Junio, 26","Julio,26",Total 2024,Total 2025,Total 2026
0,Generadas,5,6,11,23,26,43,55,36,56,...,113,83,85,74,95,82,32,519,1178,450.000000
1,Aprobadas,1,2,7,14,8,13,30,19,26,...,37,37,41,42,44,35,12,215,451,201.000000
2,Condicionadas,0,0,1,0,4,0,3,0,1,...,34,21,14,16,17,10,9,100,287,102.000000
3,Rechazadas,4,4,4,9,14,22,17,13,13,...,36,25,30,16,30,33,9,163,392,137.000000
4,Formalizadas,1,1,5,11,3,6,17,9,7,...,21,17,18,16,19,13,4,105,234,91.000000
6,% de Aprobación,0.2,0.333333,0.636364,0.608696,0.307692,0.302326,0.545455,0.527778,0.464286,...,0.327434,0.445783,0.482353,0.567568,0.463158,0.426829,0.375,0.414258,0.382852,0.446667
7,% de Formalizacion,1,0.5,0.714286,0.785714,0.375,0.461538,0.566667,0.473684,0.269231,...,0.567568,0.459459,0.439024,0.380952,0.431818,0.371429,0.333333,0.488372,0.518847,0.452736
9,N.º de solicitudes ingresadas por financiera,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Financiera,0,0,0,0,0,0,0,0,51,...,113,83,85,74,95,82,32,TOTAL,% PARTICIPACION,NaN
13,ABC,-,-,-,-,-,-,-,-,-,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0.000518,NaN
14,Afirme,-,-,-,-,-,-,-,-,18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,121,0.062727,NaN
15,Banorte,-,-,-,-,-,-,-,-,1,...,53,33,33,33,34,15,10,790,0.409539,NaN
16,BBVA,-,-,-,-,-,-,-,-,12,...,7,10,12,7,11,16,3,202,0.104717,NaN
17,Ensueño,-,-,-,-,-,-,-,-,-,...,9,4,3,1,8,8,7,144,0.07465,NaN
18,FinanMadrid,-,-,-,-,-,-,-,-,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,0.001037,NaN
19,INBURSA,-,-,-,-,-,-,-,-,-,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN
20,MSTART,-,-,-,-,-,-,-,-,-,...,12,12,9,5,11,6,1,156,0.080871,NaN
21,Nexu,-,-,-,-,-,-,-,-,19,...,1,NaN,NaN,NaN,NaN,NaN,NaN,135,0.069984,NaN
22,Santander,-,-,-,-,-,-,-,-,1,...,26,18,25,21,18,30,7,442,0.229134,NaN
23,Scotiabank,-,-,-,-,-,-,-,-,-,...,3,2,1,3,9,6,4,41,0.021255,NaN
24,Sumafin,-,-,-,-,-,-,-,-,-,...,2,4,1,NaN,NaN,NaN,NaN,7,0.003629,NaN
25,Bajio,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1,NaN,NaN,NaN,NaN,1,0.000518,NaN
26,Kuna,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,4,4,1,NaN,9,0.004666,NaN
28,Motivos de SDC No autorizadas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,Mal Buro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,33,19,15,12,12,22,NaN,311,NaN,NaN
31,Score bajo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5,3,10,4,10,4,NaN,66,NaN,NaN
32,Capacidad de pago,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,2,3,NaN,6,6,NaN,17,NaN,NaN
33,Otros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,1,2,NaN,1,1,NaN,7,NaN,NaN
36,Motivos de SDC No formaliadas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,Compra en otro lado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4,1,1,2,2,2,NaN,44,NaN,NaN
39,Falta importe para enganche,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,0,3,1,2,NaN,6,NaN,NaN
40,Espera comprar en futuro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9,6,4,10,1,7,NaN,41,NaN,NaN
41,Otros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,5,11,3,9,5,NaN,41,NaN,NaN

In [7]:
#Identificar valores nulos por columna
valores_nulos=df3.isnull().sum()
valores_nulos

Indicador           0
Enero, 24          13
Febrero, 24        13
Marzo, 24          13
Abril, 24          13
Mayo, 24           13
Junio, 24          13
Julio, 24          13
Agosto, 24         13
Septiembre, 24     14
Octubre, 24        13
Noviembre, 24      14
Diciembre, 25      14
Enero, 25          14
Febrero, 25        14
Marzo, 25          14
Abril, 25          14
Mayo, 25            8
Junio, 25           9
Julio, 25           8
Agosto, 25         10
Septiembre, 25      6
Octubre, 25        10
Noviembre, 25       9
Diciembre, 25.1    13
Enero, 26           9
Febrero, 26        10
Marzo, 26           9
Abril, 26          12
Mayo,26            10
Junio, 26          10
Julio,26           19
Total 2024          3
Total 2025         11
Total 2026         26
dtype: int64

In [8]:
#Identificar valores nulos por dataframe
valores_nulos=df3.isnull().sum().sum()
valores_nulos

np.int64(407)

In [9]:
#Realizamos una copia del dataframe
df4=df3.copy()

In [10]:
#Cuarto método de sustitución de valores nulos
#Sustituir valores nulos por un string en  concreto 
df4["Enero, 24"] =df4["Enero, 24"].fillna("-")

In [11]:
#Cuarto método de sustitución de valores nulos
#Sustituir valores nulos por un string en  concreto 
df4["Febrero, 24"] =df4["Febrero, 24"].fillna("-")

In [12]:
#Cuarto método de sustitución de valores nulos
#Sustituir valores nulos por un string en  concreto 
df4["Marzo, 24"] =df4["Marzo, 24"].fillna("-")

In [13]:
#Cuarto método de sustitución de valores nulos
#Sustituir valores nulos por un string en  concreto 
df4["Abril, 24"] =df4["Abril, 24"].fillna("-")

In [14]:
#Cuarto método de sustitución de valores nulos
#Sustituir valores nulos por un string en  concreto 
df4["Mayo, 24"] =df4["Mayo, 24"].fillna("-")

In [15]:
#Cuarto método de sustitución de valores nulos
#Sustituir valores nulos por un string en  concreto 
df4["Junio, 24"] =df4["Junio, 24"].fillna("-")

In [16]:
#Cuarto método de sustitución de valores nulos
#Sustituir valores nulos por un string en  concreto 
df4["Julio, 24"] =df4["Julio, 24"].fillna("-")

In [17]:
#Cuarto método de sustitución de valores nulos
#Sustituir valores nulos por un string en  concreto 
df4["Agosto, 24"] =df4["Agosto, 24"].fillna("-")

In [18]:
#Cuarto método de sustitución de valores nulos
#Sustituir valores nulos por un string en  concreto 
df4["Septiembre, 24"] =df4["Septiembre, 24"].fillna("-")

In [19]:
#Cuarto método de sustitución de valores nulos
#Sustituir valores nulos por un string en  concreto 
df4["Octubre, 24"] =df4["Octubre, 24"].fillna("-")

In [20]:
#Cuarto método de sustitución de valores nulos
#Sustituir valores nulos por un string en  concreto 
df4["Noviembre, 24"] =df4["Noviembre, 24"].fillna("-")

In [21]:
#Cuarto método de sustitución de valores nulos
#Sustituir valores nulos por un string en  concreto 
df4["Diciembre, 25"] =df4["Diciembre, 25"].fillna("-")

In [22]:
#Cuarto método de sustitución de valores nulos
#Sustituir valores nulos por un string en  concreto 
df4["Enero, 25"] =df4["Enero, 25"].fillna("-")

In [23]:
#Cuarto método de sustitución de valores nulos
#Sustituir valores nulos por un string en  concreto 
df4["Febrero, 25"] =df4["Febrero, 25"].fillna("-")

In [24]:
#Cuarto método de sustitución de valores nulos
#Sustituir valores nulos por un string en  concreto 
df4["Marzo, 25"] =df4["Marzo, 25"].fillna("-")

In [25]:
#Cuarto método de sustitución de valores nulos
#Sustituir valores nulos por un string en  concreto 
df4["Abril, 25"] =df4["Abril, 25"].fillna("-")

In [26]:
#Cuarto método de sustitución de valores nulos
#Sustituir valores nulos por un string en  concreto 
df4["Mayo, 25"] =df4["Mayo, 25"].fillna("-")

In [27]:
#Cuarto método de sustitución de valores nulos
#Sustituir valores nulos por un string en  concreto 
df4["Junio, 25"] =df4["Junio, 25"].fillna("-")

In [28]:
#Cuarto método de sustitución de valores nulos
#Sustituir valores nulos por un string en  concreto 
df4["Julio, 25"] =df4["Julio, 25"].fillna("-")

In [29]:
#Cuarto método de sustitución de valores nulos
#Sustituir valores nulos por un string en  concreto 
df4["Agosto, 25"] =df4["Agosto, 25"].fillna("-")

In [30]:
#Cuarto método de sustitución de valores nulos
#Sustituir valores nulos por un string en  concreto 
df4["Septiembre, 25"] =df4["Septiembre, 25"].fillna("-")

In [31]:
#Cuarto método de sustitución de valores nulos
#Sustituir valores nulos por un string en  concreto 
df4["Octubre, 25"] =df4["Octubre, 25"].fillna("-")

In [32]:
#Cuarto método de sustitución de valores nulos
#Sustituir valores nulos por un string en  concreto 
df4["Noviembre, 25"] =df4["Noviembre, 25"].fillna("-")

In [33]:
#Cuarto método de sustitución de valores nulos
#Sustituir valores nulos por un string en  concreto 
df4["Diciembre, 25.1"] =df4["Diciembre, 25.1"].fillna("-")

In [34]:
#Cuarto método de sustitución de valores nulos
#Sustituir valores nulos por un string en  concreto 
df4["Enero, 26"] =df4["Enero, 26"].fillna("-")

In [35]:
#Cuarto método de sustitución de valores nulos
#Sustituir valores nulos por un string en  concreto 
df4["Enero, 26"] =df4["Enero, 26"].fillna("-")

In [36]:
#Cuarto método de sustitución de valores nulos
#Sustituir valores nulos por un string en  concreto 
df4["Febrero, 26"] =df4["Febrero, 26"].fillna("-")

In [37]:
#Cuarto método de sustitución de valores nulos
#Sustituir valores nulos por un string en  concreto 
df4["Marzo, 26"] =df4["Marzo, 26"].fillna("-")

In [38]:
#Cuarto método de sustitución de valores nulos
#Sustituir valores nulos por un string en  concreto 
df4["Abril, 26"] =df4["Abril, 26"].fillna("-")

In [39]:
#Cuarto método de sustitución de valores nulos
#Sustituir valores nulos por un string en  concreto 
df4["Mayo,26"] =df4["Mayo,26"].fillna("-")

In [40]:
#Cuarto método de sustitución de valores nulos
#Sustituir valores nulos por un string en  concreto 
df4["Junio, 26"] =df4["Junio, 26"].fillna("-")

In [41]:
#Cuarto método de sustitución de valores nulos
#Sustituir valores nulos por un string en  concreto 
df4["Julio,26"] =df4["Julio,26"].fillna("-")

In [42]:
#Cuarto método de sustitución de valores nulos
#Sustituir valores nulos por un string en  concreto 
df4["Total 2024"] =df4["Total 2024"].fillna("-")

In [43]:
#Cuarto método de sustitución de valores nulos
#Sustituir valores nulos por un string en  concreto 
df4["Total 2025"] =df4["Total 2025"].fillna("-")

In [44]:
#Cuarto método de sustitución de valores nulos
#Sustituir valores nulos por un string en  concreto 
df4["Total 2026"] =df4["Total 2026"].fillna("-")

In [45]:
#Corroboramos valores nulos
valores_nulos=df4.isnull().sum()
valores_nulos

Indicador          0
Enero, 24          0
Febrero, 24        0
Marzo, 24          0
Abril, 24          0
Mayo, 24           0
Junio, 24          0
Julio, 24          0
Agosto, 24         0
Septiembre, 24     0
Octubre, 24        0
Noviembre, 24      0
Diciembre, 25      0
Enero, 25          0
Febrero, 25        0
Marzo, 25          0
Abril, 25          0
Mayo, 25           0
Junio, 25          0
Julio, 25          0
Agosto, 25         0
Septiembre, 25     0
Octubre, 25        0
Noviembre, 25      0
Diciembre, 25.1    0
Enero, 26          0
Febrero, 26        0
Marzo, 26          0
Abril, 26          0
Mayo,26            0
Junio, 26          0
Julio,26           0
Total 2024         0
Total 2025         0
Total 2026         0
dtype: int64

In [46]:
#Corroboramos valores nulos en todo el dataframe
valores_nulos=df4.isnull().sum().sum()
valores_nulos

np.int64(0)

In [47]:
#Convertir DataFrame a CSV
df4.to_csv("SDC_sin_nulos.csv")