In [146]:
#Importamos las librerias pandas, numpy y matplotlib respectivamente
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [147]:
#Carga desde un archivo .xlsx sin indice
df = pd.read_excel('Ventas_por_Asesor.xlsx')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 39 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Ventas X Mes   53 non-null     str
 1   12             33 non-null     object
 2   7              32 non-null     object
 3   8              32 non-null     object
 4   13             32 non-null     object
 5   6              32 non-null     object
 6   21             32 non-null     object
 7   17             32 non-null     object
 8   17.1           32 non-null     object
 9   23             32 non-null     object
 10  22             32 non-null     object
 11  32             32 non-null     object
 12  26             33 non-null     object
 13  20             32 non-null     object
 14  30             31 non-null     object
 15  30.1           34 non-null     object
 16  34             32 non-null     object
 17  40             15 non-null     object
 18  36             14 non-null     object
 19  27             13 non-null     object
 20  38             16 non-null     object
 21  40.1           16 non-null     object
 22  42             14 non-null     object
 23  34.1           15 non-null     object
 24  38.1           14 non-null     object
 25  34.2           16 non-null     object
 26  41             16 non-null     object
 27  41.1           16 non-null     object
 28  35             13 non-null     object
 29  37             15 non-null     object
 30  10             9 non-null      object
 31  Unnamed: 31    52 non-null     float64
 32  Unnamed: 32    50 non-null     object
 33  Unnamed: 33    54 non-null     object
 34  Unnamed: 34    50 non-null     object
 35  Unnamed: 35    54 non-null     object
 36  Unnamed: 36    51 non-null     object
 37  Unnamed: 37    54 non-null     object
 38  Unnamed: 38    50 non-null     object
dtypes: float64(1), object(37), str(1)
memory usage: 16.6+ KB

In [148]:
df

,Ventas X Mes,12,7,8,13,6,21,17,17.1,23,...,37,10,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38
0,NaN,2024-02-01 00:00:00,2024-03-01 00:00:00,2024-04-01 00:00:00,2024-05-01 00:00:00,2024-06-01 00:00:00,2024-07-01 00:00:00,2024-08-01 00:00:00,2024-09-01 00:00:00,2024-10-01 00:00:00,...,2026-06-01 00:00:00,2026-07-01 00:00:00,NaN,NaN,2024,NaN,2025,NaN,2026,NaN
1,Nombre vendedor,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,811.0,Raking,Acum,Ranking,Acum,Ranking,Acum,Ranking
2,PEDRO GONZALEZ ESPINDOLA,,,1,2,,7,2,3,3,...,4,NaN,88.0,NaN,22,NaN,45,3,21,NaN
3,VICTOR MANUEL SANCHEZ ARRO,,,,,1,1,3,,2,...,3,2,88.0,NaN,11,NaN,51,NaN,26,NaN
4,MIGUEL ANGEL SONDEREGGER,,,,1,2,7,5,2,2,...,NaN,NaN,28.0,6,27,2,1,26,0,18
5,JOSE ANTONIO LICONA MENDE,1,,,2,,,,3,2,...,9,1,98.0,1,10,5,35,5,53,2
6,JAIME GONZALEZ CORONA,,2,3,5,2,3,3,3,4,...,NaN,NaN,25.0,8,25,3,0,31,0,18
7,ALAN GONZÁLEZ BELANZATEGU,,,,,,,,,,...,NaN,NaN,46.0,4,4,11,36,4,6,12
8,MAURICIO ALFREDO VAZQUEZ F,,,,,,,,,,...,3,3,72.0,2,0,25,47,2,25,3
9,AURELIO FELIPE TORRES REV,,,,,,,,,3,...,1,1,63.0,3,3,13,45,3,15,4
10,J4OSETTE RAMON NAVA FLORES,,,,,,2,4,2,1,...,NaN,NaN,16.0,11,16,4,0,31,0,18
11,CARLOS ALBERTO NIETO MERI,,,,,,,,2,2,...,NaN,NaN,15.0,12,10,5,5,13,0,18
12,NANCY OLASCOAGA CASTILLO,,,,,,,,,1,...,NaN,NaN,20.0,9,3,13,17,7,0,18
13,DANIEL DE LEON CANDIA,,,,,,,,,3,...,NaN,NaN,12.0,15,9,7,3,19,0,18
14,DANIELA DURAN BERNARDINO,5,2,1,,,,,,,...,NaN,NaN,8.0,21,8,8,0,31,0,18
15,GUADALUPE PALACIOS HERNÁN,,,,,,,,,,...,NaN,NaN,7.0,22,5,10,2,20,0,18
16,CARLOS CORTES TEXIS,,,,,,,,,,...,NaN,NaN,7.0,22,1,19,6,12,0,18
17,RICARDO SILVA HERAS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,20.0,9,0,25,20,6,0,18
18,PAUL ROSAS YRIGOYEN,,1,3,2,,,,,,...,NaN,NaN,6.0,24,6,9,0,31,0,18
19,OSCAR ALONSO VELÁZQUEZ HE,,,,,,,,,,...,NaN,NaN,6.0,24,4,11,2,20,0,18
20,JOSE MANUEL LOPEZ AGUILA,3,,,,,,,,,...,NaN,NaN,3.0,31,3,13,0,31,0,18
21,JESUS SERRANO RAMIREZ,2,,,,,,,,,...,NaN,NaN,2.0,32,2,16,0,31,0,18
22,LUIS ALBERTO GOMEZ GONZAL,,2,,,,,,,,...,NaN,NaN,2.0,32,2,16,0,31,0,18
23,MONICA GISELA FLORES RODR,,,,,,,,2,,...,NaN,NaN,2.0,32,2,16,0,31,0,18
24,iGOR SEBASTIÁN BENHUMEA Z,,,,,,,,,,...,NaN,NaN,2.0,32,0,25,2,20,0,18
25,CLAUDIA GALVÁN ARCE,,,,,,,,,,...,NaN,NaN,2.0,32,0,25,2,20,0,18
26,MIGUEL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,4.0,28,0,25,4,16,0,18
27,SERGIO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,2.0,32,0,25,2,20,0,18
28,DAVID JIMENEZ CASTRO,,,,1,,,,,,...,NaN,NaN,1.0,41,1,19,0,31,0,18
29,ABIGAIL VARGAS CRUZ,,,,,1,,,,,...,NaN,NaN,1.0,41,1,19,0,31,0,18
30,NAYELI MONTES DE OCA MART,1,,,,,,,,,...,NaN,NaN,1.0,41,1,19,0,31,0,18
31,ANGELICA MAGDALENA CEDILL,,,,,,,,,,...,NaN,NaN,1.0,41,1,19,0,31,0,18
32,JOSE CARLOS ZENTENO LOZAD,,,,,,1,,,,...,NaN,NaN,1.0,41,1,19,0,31,0,18
33,ANGEL EDUARDO VAZQUEZ REY,,,,,,,,,,...,NaN,NaN,1.0,41,0,25,1,26,0,18
34,JOSE EDUARDO PARADA DURAN,,,,,,,,,,...,NaN,NaN,1.0,41,0,25,1,26,0,18
35,LAURA LOPEZ MEJIA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.0,41,0,25,1,26,0,18
36,IGNACIO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,14.0,13,0,25,8,11,6,12
37,MARCOS COCA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,9.0,19,0,25,9,10,0,18
38,CESAR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,4.0,28,0,25,4,16,0,18
39,JULIO CESAR PESTAÑA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1,NaN,29.0,5,0,25,16,8,13,5
40,JULIO CESAR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2,NaN,12.0,15,0,25,5,13,7,11
41,JOSHLAAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,2.0,32,0,25,2,20,0,18
42,OMAR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,5.0,26,0,25,5,13,0,18
43,MERCEDES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,4.0,28,0,25,4,16,0,18
44,ALVARO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,5.0,26,0,25,1,26,4,14
45,CARLOS MEJIA (PACHUCA),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3,NaN,10.0,18,0,25,0,31,10,9
46,MARIO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4,NaN,9.0,19,0,25,0,31,9,10
47,CARLOS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3,NaN,12.0,15,0,25,0,31,12,7
48,NAYELI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1,13.0,14,0,25,0,31,13,5
49,PEDRO ANTONIO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2,1,26.0,7,0,25,15,9,11,8
50,OBRIAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1,NaN,2.0,32,0,25,0,31,2,15
51,FATIMA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1,1,2.0,32,0,25,0,31,2,15
52,RUBEN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.0,41,0,25,0,31,1,17
53,Total general,12,7,8,13,6,21,17,17,23,...,37,10,NaN,NaN,178,NaN,397,NaN,236,NaN

In [149]:
#Eliminar primera fila o filas innecesarias
df1= pd.read_excel('Ventas_por_Asesor.xlsx', skiprows=1)
df1

,Unnamed: 0,2024-02-01 00:00:00,2024-03-01 00:00:00,2024-04-01 00:00:00,2024-05-01 00:00:00,2024-06-01 00:00:00,2024-07-01 00:00:00,2024-08-01 00:00:00,2024-09-01 00:00:00,2024-10-01 00:00:00,...,2026-06-01 00:00:00,2026-07-01 00:00:00,Unnamed: 31,Unnamed: 32,2024,Unnamed: 34,2025,Unnamed: 36,2026,Unnamed: 38
0,Nombre vendedor,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,811.0,Raking,Acum,Ranking,Acum,Ranking,Acum,Ranking
1,PEDRO GONZALEZ ESPINDOLA,,,1,2,,7,2,3,3,...,4.0,NaN,88.0,NaN,22,NaN,45,3,21,NaN
2,VICTOR MANUEL SANCHEZ ARRO,,,,,1,1,3,,2,...,3.0,2.0,88.0,NaN,11,NaN,51,NaN,26,NaN
3,MIGUEL ANGEL SONDEREGGER,,,,1,2,7,5,2,2,...,NaN,NaN,28.0,6,27,2,1,26,0,18
4,JOSE ANTONIO LICONA MENDE,1,,,2,,,,3,2,...,9.0,1.0,98.0,1,10,5,35,5,53,2
5,JAIME GONZALEZ CORONA,,2,3,5,2,3,3,3,4,...,NaN,NaN,25.0,8,25,3,0,31,0,18
6,ALAN GONZÁLEZ BELANZATEGU,,,,,,,,,,...,NaN,NaN,46.0,4,4,11,36,4,6,12
7,MAURICIO ALFREDO VAZQUEZ F,,,,,,,,,,...,3.0,3.0,72.0,2,0,25,47,2,25,3
8,AURELIO FELIPE TORRES REV,,,,,,,,,3,...,1.0,1.0,63.0,3,3,13,45,3,15,4
9,J4OSETTE RAMON NAVA FLORES,,,,,,2,4,2,1,...,NaN,NaN,16.0,11,16,4,0,31,0,18
10,CARLOS ALBERTO NIETO MERI,,,,,,,,2,2,...,NaN,NaN,15.0,12,10,5,5,13,0,18
11,NANCY OLASCOAGA CASTILLO,,,,,,,,,1,...,NaN,NaN,20.0,9,3,13,17,7,0,18
12,DANIEL DE LEON CANDIA,,,,,,,,,3,...,NaN,NaN,12.0,15,9,7,3,19,0,18
13,DANIELA DURAN BERNARDINO,5,2,1,,,,,,,...,NaN,NaN,8.0,21,8,8,0,31,0,18
14,GUADALUPE PALACIOS HERNÁN,,,,,,,,,,...,NaN,NaN,7.0,22,5,10,2,20,0,18
15,CARLOS CORTES TEXIS,,,,,,,,,,...,NaN,NaN,7.0,22,1,19,6,12,0,18
16,RICARDO SILVA HERAS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,20.0,9,0,25,20,6,0,18
17,PAUL ROSAS YRIGOYEN,,1,3,2,,,,,,...,NaN,NaN,6.0,24,6,9,0,31,0,18
18,OSCAR ALONSO VELÁZQUEZ HE,,,,,,,,,,...,NaN,NaN,6.0,24,4,11,2,20,0,18
19,JOSE MANUEL LOPEZ AGUILA,3,,,,,,,,,...,NaN,NaN,3.0,31,3,13,0,31,0,18
20,JESUS SERRANO RAMIREZ,2,,,,,,,,,...,NaN,NaN,2.0,32,2,16,0,31,0,18
21,LUIS ALBERTO GOMEZ GONZAL,,2,,,,,,,,...,NaN,NaN,2.0,32,2,16,0,31,0,18
22,MONICA GISELA FLORES RODR,,,,,,,,2,,...,NaN,NaN,2.0,32,2,16,0,31,0,18
23,iGOR SEBASTIÁN BENHUMEA Z,,,,,,,,,,...,NaN,NaN,2.0,32,0,25,2,20,0,18
24,CLAUDIA GALVÁN ARCE,,,,,,,,,,...,NaN,NaN,2.0,32,0,25,2,20,0,18
25,MIGUEL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,4.0,28,0,25,4,16,0,18
26,SERGIO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,2.0,32,0,25,2,20,0,18
27,DAVID JIMENEZ CASTRO,,,,1,,,,,,...,NaN,NaN,1.0,41,1,19,0,31,0,18
28,ABIGAIL VARGAS CRUZ,,,,,1,,,,,...,NaN,NaN,1.0,41,1,19,0,31,0,18
29,NAYELI MONTES DE OCA MART,1,,,,,,,,,...,NaN,NaN,1.0,41,1,19,0,31,0,18
30,ANGELICA MAGDALENA CEDILL,,,,,,,,,,...,NaN,NaN,1.0,41,1,19,0,31,0,18
31,JOSE CARLOS ZENTENO LOZAD,,,,,,1,,,,...,NaN,NaN,1.0,41,1,19,0,31,0,18
32,ANGEL EDUARDO VAZQUEZ REY,,,,,,,,,,...,NaN,NaN,1.0,41,0,25,1,26,0,18
33,JOSE EDUARDO PARADA DURAN,,,,,,,,,,...,NaN,NaN,1.0,41,0,25,1,26,0,18
34,LAURA LOPEZ MEJIA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.0,41,0,25,1,26,0,18
35,IGNACIO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,14.0,13,0,25,8,11,6,12
36,MARCOS COCA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,9.0,19,0,25,9,10,0,18
37,CESAR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,4.0,28,0,25,4,16,0,18
38,JULIO CESAR PESTAÑA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,NaN,29.0,5,0,25,16,8,13,5
39,JULIO CESAR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,NaN,12.0,15,0,25,5,13,7,11
40,JOSHLAAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,2.0,32,0,25,2,20,0,18
41,OMAR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,5.0,26,0,25,5,13,0,18
42,MERCEDES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,4.0,28,0,25,4,16,0,18
43,ALVARO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,5.0,26,0,25,1,26,4,14
44,CARLOS MEJIA (PACHUCA),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,NaN,10.0,18,0,25,0,31,10,9
45,MARIO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.0,NaN,9.0,19,0,25,0,31,9,10
46,CARLOS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,NaN,12.0,15,0,25,0,31,12,7
47,NAYELI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.0,13.0,14,0,25,0,31,13,5
48,PEDRO ANTONIO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,1.0,26.0,7,0,25,15,9,11,8
49,OBRIAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,NaN,2.0,32,0,25,0,31,2,15
50,FATIMA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,1.0,2.0,32,0,25,0,31,2,15
51,RUBEN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.0,41,0,25,0,31,1,17
52,Total general,12,7,8,13,6,21,17,17,23,...,37.0,10.0,NaN,NaN,178,NaN,397,NaN,236,NaN

In [150]:
#Identificar valores nulos por columna
valores_nulos=df1.isnull().sum()
valores_nulos

Unnamed: 0              0
2024-02-01 00:00:00    21
2024-03-01 00:00:00    22
2024-04-01 00:00:00    22
2024-05-01 00:00:00    22
2024-06-01 00:00:00    22
2024-07-01 00:00:00    22
2024-08-01 00:00:00    22
2024-09-01 00:00:00    22
2024-10-01 00:00:00    22
2024-11-01 00:00:00    22
2024-12-01 00:00:00    22
2025-01-01 00:00:00    21
2025-02-01 00:00:00    22
2025-03-01 00:00:00    23
2025-04-01 00:00:00    20
2025-05-01 00:00:00    22
2025-06-01 00:00:00    39
2025-07-01 00:00:00    40
2025-08-01 00:00:00    41
2025-09-01 00:00:00    38
2025-10-01 00:00:00    38
2025-11-01 00:00:00    40
2025-12-01 00:00:00    39
2026-01-01 00:00:00    40
2026-02-01 00:00:00    38
2026-03-01 00:00:00    38
2026-04-01 00:00:00    38
2026-05-01 00:00:00    41
2026-06-01 00:00:00    39
2026-07-01 00:00:00    45
Unnamed: 31             1
Unnamed: 32             3
2024                    0
Unnamed: 34             3
2025                    0
Unnamed: 36             2
2026                    0
Unnamed: 38             3
dtype: int64

In [151]:
#Identificar valores nulos por dataframe
valores_nulos=df1.isnull().sum().sum()
valores_nulos

np.int64(915)

In [152]:
#Realizamos una copia del dataframe
df2=df1.copy()

In [153]:
# 1. Convertir los nombres de todas las columnas a texto
df2.columns = df2.columns.astype(str)

In [161]:
#Tercer método de sustitución de valores nulos
#Sustituir valores nulos por un valor numérico en  concreto 
df2['2024-02-01 00:00:00'] = df2['2024-02-01 00:00:00'].fillna(0)

In [162]:
#Tercer método de sustitución de valores nulos
#Sustituir valores nulos por un valor numérico en  concreto 
df2['2024-03-01 00:00:00'] = df2['2024-03-01 00:00:00'].fillna(0)

In [163]:
#Tercer método de sustitución de valores nulos
#Sustituir valores nulos por un valor numérico en  concreto 
df2['2024-04-01 00:00:00'] = df2['2024-04-01 00:00:00'].fillna(0)

In [164]:
#Tercer método de sustitución de valores nulos
#Sustituir valores nulos por un valor numérico en  concreto 
df2['2024-05-01 00:00:00'] = df2['2024-05-01 00:00:00'].fillna(0)

In [165]:
#Tercer método de sustitución de valores nulos
#Sustituir valores nulos por un valor numérico en  concreto 
df2['2024-06-01 00:00:00'] = df2['2024-06-01 00:00:00'].fillna(0)

In [166]:
#Tercer método de sustitución de valores nulos
#Sustituir valores nulos por un valor numérico en  concreto 
df2['2024-07-01 00:00:00'] = df2['2024-07-01 00:00:00'].fillna(0)

In [167]:
#Tercer método de sustitución de valores nulos
#Sustituir valores nulos por un valor numérico en  concreto 
df2['2024-08-01 00:00:00'] = df2['2024-08-01 00:00:00'].fillna(0)

In [168]:
#Tercer método de sustitución de valores nulos
#Sustituir valores nulos por un valor numérico en  concreto 
df2['2024-09-01 00:00:00'] = df2['2024-09-01 00:00:00'].fillna(0)

In [169]:
#Tercer método de sustitución de valores nulos
#Sustituir valores nulos por un valor numérico en  concreto 
df2['2024-10-01 00:00:00'] = df2['2024-10-01 00:00:00'].fillna(0)

In [170]:
#Tercer método de sustitución de valores nulos
#Sustituir valores nulos por un valor numérico en  concreto 
df2['2024-11-01 00:00:00'] = df2['2024-11-01 00:00:00'].fillna(0)

In [171]:
#Tercer método de sustitución de valores nulos
#Sustituir valores nulos por un valor numérico en  concreto 
df2['2024-12-01 00:00:00'] = df2['2024-12-01 00:00:00'].fillna(0)

In [172]:
#Tercer método de sustitución de valores nulos
#Sustituir valores nulos por un valor numérico en  concreto 
df2['2025-01-01 00:00:00'] = df2['2025-01-01 00:00:00'].fillna(0)

In [173]:
#Tercer método de sustitución de valores nulos
#Sustituir valores nulos por un valor numérico en  concreto 
df2['2025-02-01 00:00:00'] = df2['2025-02-01 00:00:00'].fillna(0)

In [174]:
#Tercer método de sustitución de valores nulos
#Sustituir valores nulos por un valor numérico en  concreto 
df2['2025-03-01 00:00:00'] = df2['2025-03-01 00:00:00'].fillna(0)

In [175]:
#Tercer método de sustitución de valores nulos
#Sustituir valores nulos por un valor numérico en  concreto 
df2['2025-04-01 00:00:00'] = df2['2025-04-01 00:00:00'].fillna(0)

In [176]:
#Tercer método de sustitución de valores nulos
#Sustituir valores nulos por un valor numérico en  concreto 
df2['2025-05-01 00:00:00'] = df2['2025-01-01 00:00:00'].fillna(0)

In [177]:
#Tercer método de sustitución de valores nulos
#Sustituir valores nulos por un valor numérico en  concreto 
df2['2025-06-01 00:00:00'] = df2['2025-06-01 00:00:00'].fillna(0)

In [178]:
#Tercer método de sustitución de valores nulos
#Sustituir valores nulos por un valor numérico en  concreto 
df2['2025-07-01 00:00:00'] = df2['2025-07-01 00:00:00'].fillna(0)

In [179]:
#Tercer método de sustitución de valores nulos
#Sustituir valores nulos por un valor numérico en  concreto 
df2['2025-08-01 00:00:00'] = df2['2025-08-01 00:00:00'].fillna(0)

In [180]:
#Tercer método de sustitución de valores nulos
#Sustituir valores nulos por un valor numérico en  concreto 
df2['2025-09-01 00:00:00'] = df2['2025-09-01 00:00:00'].fillna(0)

In [181]:
#Tercer método de sustitución de valores nulos
#Sustituir valores nulos por un valor numérico en  concreto 
df2['2025-10-01 00:00:00'] = df2['2025-10-01 00:00:00'].fillna(0)

In [183]:
#Tercer método de sustitución de valores nulos
#Sustituir valores nulos por un valor numérico en  concreto 
df2['2025-11-01 00:00:00'] = df2['2025-11-01 00:00:00'].fillna(0)

In [184]:
#Tercer método de sustitución de valores nulos
#Sustituir valores nulos por un valor numérico en  concreto 
df2['2025-12-01 00:00:00'] = df2['2025-12-01 00:00:00'].fillna(0)

In [185]:
#Tercer método de sustitución de valores nulos
#Sustituir valores nulos por un valor numérico en  concreto 
df2['2026-01-01 00:00:00'] = df2['2026-01-01 00:00:00'].fillna(0)

In [186]:
#Tercer método de sustitución de valores nulos
#Sustituir valores nulos por un valor numérico en  concreto 
df2['2026-02-01 00:00:00'] = df2['2026-02-01 00:00:00'].fillna(0)

In [187]:
#Tercer método de sustitución de valores nulos
#Sustituir valores nulos por un valor numérico en  concreto 
df2['2026-03-01 00:00:00'] = df2['2026-03-01 00:00:00'].fillna(0)

In [188]:
#Tercer método de sustitución de valores nulos
#Sustituir valores nulos por un valor numérico en  concreto 
df2['2026-04-01 00:00:00'] = df2['2026-04-01 00:00:00'].fillna(0)

In [189]:
#Tercer método de sustitución de valores nulos
#Sustituir valores nulos por un valor numérico en  concreto 
df2['2026-05-01 00:00:00'] = df2['2026-05-01 00:00:00'].fillna(0)

In [190]:
#Tercer método de sustitución de valores nulos
#Sustituir valores nulos por un valor numérico en  concreto 
df2['2026-06-01 00:00:00'] = df2['2026-06-01 00:00:00'].fillna(0)

In [191]:
#Cuarto método de sustitución de valores nulos
#Sustituir valores nulos por un string en  concreto 
df2['2026-07-01 00:00:00'] = df2['2026-07-01 00:00:00'].fillna(0)

In [192]:
#Cuarto método de sustitución de valores nulos
#Sustituir valores nulos por un string en  concreto 
df2["Unnamed: 31"] =df2["Unnamed: 31"].fillna("-")

In [193]:
#Cuarto método de sustitución de valores nulos
#Sustituir valores nulos por un string en  concreto 
df2["Unnamed: 32"] =df2["Unnamed: 32"].fillna("-")

In [194]:
#Cuarto método de sustitución de valores nulos
#Sustituir valores nulos por un string en  concreto 
df2["Unnamed: 34"] =df2["Unnamed: 34"].fillna("-")

In [196]:
#Cuarto método de sustitución de valores nulos
#Sustituir valores nulos por un string en  concreto 
df2["Unnamed: 36"] =df2["Unnamed: 36"].fillna("-")

In [197]:
#Cuarto método de sustitución de valores nulos
#Sustituir valores nulos por un string en  concreto 
df2["Unnamed: 38"] =df2["Unnamed: 38"].fillna("-")

In [200]:
#Corroboramos valores nulos
valores_nulos=df2.isnull().sum()
valores_nulos

Unnamed: 0             0
2024-02-01 00:00:00    0
2024-03-01 00:00:00    0
2024-04-01 00:00:00    0
2024-05-01 00:00:00    0
2024-06-01 00:00:00    0
2024-07-01 00:00:00    0
2024-08-01 00:00:00    0
2024-09-01 00:00:00    0
2024-10-01 00:00:00    0
2024-11-01 00:00:00    0
2024-12-01 00:00:00    0
2025-01-01 00:00:00    0
2025-02-01 00:00:00    0
2025-03-01 00:00:00    0
2025-04-01 00:00:00    0
2025-05-01 00:00:00    0
2025-06-01 00:00:00    0
2025-07-01 00:00:00    0
2025-08-01 00:00:00    0
2025-09-01 00:00:00    0
2025-10-01 00:00:00    0
2025-11-01 00:00:00    0
2025-12-01 00:00:00    0
2026-01-01 00:00:00    0
2026-02-01 00:00:00    0
2026-03-01 00:00:00    0
2026-04-01 00:00:00    0
2026-05-01 00:00:00    0
2026-06-01 00:00:00    0
2026-07-01 00:00:00    0
Unnamed: 31            0
Unnamed: 32            0
2024                   0
Unnamed: 34            0
2025                   0
Unnamed: 36            0
2026                   0
Unnamed: 38            0
dtype: int64

In [202]:
#Corroboramos valores nulos en todo el dataframe
valores_nulos=df2.isnull().sum().sum()
valores_nulos

np.int64(0)

In [203]:
#Convertir DataFrame a CSV
df2.to_csv("Ventas_por_Asesor_sin_nulos.csv")